controller_list:
  - name: fake_robot2_manipulator_controller
    joints:
      - robot2_shoulder_pan_joint
      - robot2_shoulder_lift_joint
      - robot2_elbow_joint
      - robot2_wrist_1_joint
      - robot2_wrist_2_joint
      - robot2_wrist_3_joint
  - name: fake_robot1_manipulator_controller
    joints:
      - robot1_shoulder_pan_joint
      - robot1_shoulder_lift_joint
      - robot1_elbow_joint
      - robot1_wrist_1_joint
      - robot1_wrist_2_joint
      - robot1_wrist_3_joint
  - name: fake_robot1_eef_s_controller
    joints:
      []
  - name: fake_robot1_eef_g_controller
    joints:
      []
  - name: fake_robot1_eef_c_controller
    joints:
      []