# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  robot1_elbow_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
  robot1_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.02
  robot1_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.02
  robot1_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
  robot1_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
  robot1_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
  robot2_elbow_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
  robot2_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.02
  robot2_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.02
  robot2_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
  robot2_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
  robot2_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: true
    max_acceleration: 0.04
